name: dl_project_env 
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - -r requirements.txt
      - -e . # pip install -e .
      - -e ./torch-suite
      - -e ./torch-suite/pytorch-checkpoint